### ISSUE TITLE
How to get the picture in Figure 5  Red lines denote the ground truth.

### ISSUE THREAD

**Issue by c1a1o1** [wentaozhu/adversarial-deep-structural-networks#3]
How to get the picture in Figure 5  Red lines denote the ground truth.?

**Comment by wentaozhu** [comment]
First get the predicted probability as fchollet/keras#41 . Then use matlab "bwperim", you can get the perimeter of objects in binary image.

**Comment by c1a1o1** [comment]
thanks  for your help!
