### ISSUE TITLE
fusion的值表示什么？

### ISSUE THREAD

**Issue by lixiangamy** [wentaozhu/adversarial-deep-structural-networks#6]
fusion的值表示什么？

**Comment by wentaozhu** [comment]
Value in prediction? It is the value before sigmoid. Please read the paper first to get the details of the work.

**Comment by wentaozhu** [comment]
fusion的值是crf的potential function

**Comment by lixiangamy** [comment]
thank you!谢谢！

**Comment by lixiangamy** [comment]
fusion='late'是表示不将多个FCN融合吗?

**Comment by wentaozhu** [comment]
I think so.
